### ISSUE TITLE
Compra (Purchase requisition)

### ISSUE THREAD

**Issue by victormagallanes2** [ProveeduriaOpenERP/addons_proveeduria#8]
- Es necesario crear un formulario para las requisiciones, este formulario debe de ser usado por  todos los departamentos.
- Las requisiciones que provengan de los departamentos deben poder ser cargadas en las cotizaciones (en odoo se llaman licitaciones).
- Al momento de confirmar un pedido, automáticamente muestra un botón para recibir pedido, este botón debe eliminarse ya que esta función debe de realizarla el modulo de almacén.

**Comment by Daregny** [comment]
1.- Las compras deben depender de la Planificación anual. Para evitar sobregirar las partidas presupuestarias.

**Comment by fr33co** [comment]
Para los departamentos distintos a compras ocultar: El ids de solicitudes de presupuesto y el boton confirmar licitacion

**Comment by fr33co** [comment]
Solucionado en Merge pull request #28
